### PR TITLE
Prefix term with taxonomy title

### PR DESCRIPTION
**Pull request by metbril**
Fix list layout to properly prefix a term with the taxonomy title.

### Prerequisites

Put an `x` into the box(es) that apply:

- [x] This pull request fixes a bug.
- [ ] This pull request adds a feature.
- [ ] This pull request introduces breaking change.

### Description

Fix the list layout. Show the taxonomy title as the prefix for a term.

### Issues Resolved

-

### Checklist

Put an `x` into the box(es) that apply:

#### General

- [ ] Describe what changes are being made
- [ ] Explain why and how the changes were necessary and implemented respectively
- [ ] Reference issue with `#<ISSUE_NO>` if applicable

#### Resources

- [ ] If you have changed any SCSS code, run `make release` to regenerate all CSS files

#### Contributors

- [x] Add yourself to `CONTRIBUTORS.md` if you aren't on it already

### CODE REVIEW

**Comment by luizdepra** [comment]
Your idea here is to change the taxonomy page title? Let's take `/tags/go/` as example.

- Old: **Tags: go**
- New: **go**

Well, I prefer to keep the taxonomy name in the title to differ from other taxonomies with the same term name.

**Comment by metbril** [comment]
In my setup, with the current code:

* browse to `/tags` shows title **Tag: Tags**
* browse to `/categories` shows title **Category: Categories**
* browse to `/tags/meta` shows title **meta**

This looks like a bug to me. IMHO it should be

* `/tags` shows title **Tags** (with the list of all categories)
* `/categories` shows title **Categories**
* `/tags/meta` shows title **Tag: meta**

That's what this PR fixes.

**Comment by luizdepra** [comment]
Well, it doesn't seem like that.

Take a look at this PR deployment:
- https://deploy-preview-369--hugo-coder.netlify.app/tags/ -> title is **Tags**
- https://deploy-preview-369--hugo-coder.netlify.app/tags/go/ -> title is **go**

And here is the master deployment:
- https://hugo-coder.netlify.app/tags/ -> title is **Tags**
- https://hugo-coder.netlify.app/tags/go/ -> title is **Tag: go**

Which Hugo version are you using? And have you declared the taxonomies in your `config.toml` like in the [exampleSite config](https://github.com/luizdepra/hugo-coder/blob/master/exampleSite/config.toml#L64-L67).

**Comment by metbril** [comment]
## localhost:1313/tags

Schermafbeelding 2020-07-17 om 20 09 47

---

## localhost:1313/tags/meta

Schermafbeelding 2020-07-17 om 20 10 03

**Comment by metbril** [comment]
I cloned from master this afternoon.

**config.toml**

```
[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
```

```
$ hugo version
Hugo Static Site Generator v0.73.0/extended darwin/amd64 BuildDate: unknown
```

**Comment by metbril** [comment]
I've taken a second look at the docs at https://gohugo.io/templates/section-templates/#page-kinds and it clearly says:

Every Page in Hugo has a `.Kind` attribute.
Kind | Description | Example
-- | -- | --
home | The landing page for the home page | /index.html
page | The landing page for a given page | my-post page (/posts/my-post/index.html)
section | The landing page of a given section | posts section (/posts/index.html)
taxonomy | The landing page for a taxonomy | tags taxonomy (/tags/index.html)
term | The landing page for one taxonomy’s term | term awesome in tags taxonomy (/tags/awesome/index.html)

**Comment by metbril** [comment]
This change to Hugo is the root of all evil 

https://github.com/gohugoio/hugoDocs/commit/bc0b484d1b65fec3593ee56a1594ce3bcacc83db

**Comment by luizdepra** [comment]
Interesting. So, we need to change the minimal version to `0.73.0`.
Could you please change the version number in: theme.toml and netlify.toml.

**Comment by metbril** [comment]
> Well, it doesn't seem like that.
> 
> Take a look at this PR deployment:
> 
> * https://deploy-preview-369--hugo-coder.netlify.app/tags/ -> title is **Tags**
> * https://deploy-preview-369--hugo-coder.netlify.app/tags/go/ -> title is **go**
> 
> And here is the master branch deployment:
> 
> * https://hugo-coder.netlify.app/tags/ -> title is **Tags**
> * https://hugo-coder.netlify.app/tags/go/ -> title is **Tag: go**
> 
> Which Hugo version are you using? And have you declared the taxonomies in your `config.toml` like in the [exampleSite config](https://github.com/luizdepra/hugo-coder/blob/master/exampleSite/config.toml#L64-L67).

The PR deployment and master deployment now show similar output. 😄

**Comment by luizdepra** [comment]
Nice. Thank you.

**Pull request merged**
