### PR TITLE
Font to fork

### PR DESCRIPTION
**Pull request by DLambros91**
Added CDN for ForkAwesome and removed the FontAwesome #412 

Converted icons to ForkAwesome equivalents

Please let me know if you see anything that I missed, but I think this was all.

### CODE REVIEW

**Comment by luizdepra** [comment]
I don't  know why but your PR didn't trigger our Netlify preview. But no problem, I'm taking a look.

**Comment by luizdepra** [comment]
Nicely done! I just need you to do one more thing.

Could you please change all icons prefixes from `config.toml` to `fa` too? Look for the `[[params.social]]` items.

**Comment by DLambros91** [comment]
> Nicely done! I just need you to do one more thing.
> 
> Could you please change all icons prefixes from `config.toml` to `fa` too? Look for the `[[params.social]]` items.

I just handled it. All icons are changed to fa.

**Comment by luizdepra** [comment]
Thank you. :)

**Pull request merged**
