### PR TITLE
Add support for `onedollarstats.com` analytics

### PR DESCRIPTION
**Pull request by Olshansk**
### Prerequisites

Put an `x` into the box(es) that apply:

- [ ] This pull request fixes a bug.
- [x] This pull request adds a feature.
- [ ] This pull request introduces breaking change.

### Description

Enable [OneDollarStats](https://onedollarstats.com/) be one of the default out-of-the box options for analytics with this hugo theme.

This was mostly a `copy-pasta` of the other analytics configurations.

The only difference is the necessary script to embed retrieved from their website:

Screenshot 2024-11-24 at 1 04 32 PM

### Issues Resolved

NA

### Checklist

Put an `x` into the box(es) that apply:

#### General

- [x] Describe what changes are being made
- [ ] ~~Explain why and how the changes were necessary and implemented respectively~~
- [ ] ~~Reference issue with `#<ISSUE_NO>` if applicable~~

#### Resources

- [x] If you have changed any SCSS code, run `make release` to regenerate all CSS files

#### Contributors

- [x] Add yourself to `CONTRIBUTORS.md` if you aren't on it already

### CODE REVIEW

**Comment by Olshansk** [comment]
@luizdepra Would really appreciate if you could take a look at this one!

**Comment by luizdepra** [comment]
Looks good. Thank you.

I manually merged your changes and fixed the conflicts. See [here](https://github.com/luizdepra/hugo-coder/commits/main). So, I'm closing this PR.

**Comment by Olshansk** [comment]
Awesome, thanks @luizdepra!

**Comment by Olshansk** [comment]
@luizdepra Do I have to wait for a new release in order for me to integrate this into my site?

**Comment by luizdepra** [comment]
Nop, @luizdepra. Just point to the main branch, last commit.
I'm only creating releases to pin historic version.

**Comment by Olshansk** [comment]
Thanks @luizdepra!

For anyone else that comes by this, I did have to do a couple of things.

1. Update the submodules

```bash
git submodule update --remote --merge
```

2. Update `HUGO_VERSION` in `hugo.yaml` from `0.111.3` to `0.139.3`

**Pull request closed without merging**
