### PR TITLE
Add missing integrity attributes

### PR DESCRIPTION
**Pull request by 0rzech**
### Prerequisites

Put an `x` into the box(es) that apply:

- [x] This pull request fixes a bug.
- [ ] This pull request adds a feature.
- [ ] This pull request introduces breaking change.

### Description

Adds missing `integrity` attributes to minified `dark-mode.js` and `forkawesome-webfont.woff2`.

### Issues Resolved

N/A

### Checklist

Put an `x` into the box(es) that apply:

#### General

- [x] Describe what changes are being made
- [ ] Explain why and how the changes were necessary and implemented respectively
- [ ] Reference issue with `#<ISSUE_NO>` if applicable

#### Resources

- [ ] If you have changed any SCSS code, run `make release` to regenerate all CSS files

#### Contributors

- [ ] Add yourself to `CONTRIBUTORS.md` if you aren't on it already

### CODE REVIEW

**Comment by luizdepra** [comment]
Nice. Thank you.

**Comment by lazyyz** [comment]
After add intergrity attributes, Chrome console show this warning:

<link rel="preload" href="/fonts/forkawesome-webfont.woff2?v=1.1.7" as="font" type="font/woff2" integrity="sha256-hEIt6X6xzye8ubyk8/uxjz68cRZHsJxoKS9fQ8idUGQ=" crossorigin>

The `integrity` attribute is currently ignored for preload destinations that do not support subresource integrity. See https://crbug.com/981419 for more information

How to fix it? Thanks!

**Comment by luizdepra** [comment]
@lazyyz Could please open an issue about this problem?

**Comment by lazyyz** [comment]
> @lazyyz Could please open an issue about this problem?

Done.

**Pull request merged**
