### PR TITLE
Minor CSS bug fix

### PR DESCRIPTION
**Pull request by ajdintrejic**
### Prerequisites

Put an `x` into the box(es) that apply:

- [x] This pull request fixes a bug.
- [ ] This pull request adds a feature.
- [ ] This pull request introduces breaking change.

### Description

This pull request fixes a bug that happens on mobile devices when you open and close the hamburger menu and it makes the hamburger menu blue.

image

I have removed the CSS selectors which were causing the bug. I have no idea why they were there.

### Issues Resolved
https://github.com/luizdepra/hugo-coder/issues/329

### Checklist

Put an `x` into the box(es) that apply:

#### General

- [ ] Describe what changes are being made
- [ ] Explain why and how the changes were necessary and implemented respectively
- [ ] Reference issue with `#<ISSUE_NO>` if applicable

#### Resources

- [x] If you have changed any SCSS code, run `make release` to regenerate all CSS files

#### Contributors

- [ ] Add yourself to `CONTRIBUTORS.md` if you aren't on it already

I'm not on the list, I'm not sure if I did contribute enough to be there.

### CODE REVIEW

**Comment by clement-pannetier** [comment]
Hi @ajdintrejic, by removing these lines, you "fix" the issue on mobile, but on desktop you are removing the hover functionnality !

**Comment by ajdintrejic** [comment]
Will take a look at it! Thanks.

**Comment by ajdintrejic** [comment]
The thing is, if the code is removed, it works on mobile devices, and browsers with width > 768px, and 
if we leave the code it's buggy on phones (which are majority of traffic). Does anyone have any idea how to fix this?

**Comment by luizdepra** [comment]
Enclosing the `hover, focus` rule with `@media (hover:hover) { ... }` should do the trick.

**Comment by luizdepra** [comment]
Is this still a problem?

**Comment by sdwolfz** [comment]
@luizdepra I can still reproduce the issue on mobile (honestly it's not that bad, but it does happen).

Steps:
1. Open on mobile
2. Tap on Burger to open
3. Wait until the open animation finishes
4. Tap on burger to close.
5. Notice the burger link is marked as hover and blue (that's how hover works on mobile).

**Comment by sdwolfz** [comment]
Here's my attempt at fixing this: https://github.com/luizdepra/hugo-coder/pull/446

**Comment by luizdepra** [comment]
Solved at #446.

**Pull request closed without merging**
