### PR TITLE
Add missing i18n strings for zh-cn

### LINKED ISSUE #417: [v2] Fix missing i18n strings
There are some missing translations. We should find them, translate and add default values.

### PR DESCRIPTION
**Pull request by PanZiwei**
### Prerequisites

Put an `x` into the box(es) that apply:

- [x] This pull request fixes a bug.
- [ ] This pull request adds a feature.
- [ ] This pull request introduces breaking change.

### Description

Added missing i18n strings for zh-cn, and update contributor.

### Issues Resolved

#417

### Checklist

Put an `x` into the box(es) that apply:

#### General

- [x] Describe what changes are being made
- [x] Explain why and how the changes were necessary and implemented respectively
- [x] Reference issue with `#<ISSUE_NO>` if applicable

#### Resources

- [ ] If you have changed any SCSS code, run `make release` to regenerate all CSS files

#### Contributors

- [x] Add yourself to `CONTRIBUTORS.md` if you aren't on it already

### CODE REVIEW

**Comment by alfunx** [comment]
I think this is a subset of #500.

**Comment by luizdepra** [comment]
Yup, @alfunx. It is almost the same thing.

@PanZiwei, could you tell us what is the difference here and which option is the right one? So, could you fix the conflicts for us?

```
[head_back]
<<<<<<< master
other = "返回 <a href=\"{{ . }}\">主页</a>."
=======
other = "返回 <a href=\"{{ . }}\">首页</a>."
>>>>>>> master
```

**Comment by PanZiwei** [comment]
@luizdepra 
Hi, sorry I didn't notice that it is already fixed by some else. I think either translation is OK.

**Comment by luizdepra** [comment]
Ok, @PanZiwei. So, I'm going to close this PR.
Thank you for the help. :)

**Pull request closed without merging**
