### PR TITLE
Update Bangla Translation

### PR DESCRIPTION
**Pull request by arafat-hasan**
### Prerequisites

Put an `x` into the box(es) that apply:

- [x] This pull request fixes a bug.
- [ ] This pull request adds a feature.
- [ ] This pull request introduces breaking change.

### Description

Update Bangla (Bengali) translation.

### Issues Resolved

Issues: #417

### Checklist

Put an `x` into the box(es) that apply:

#### General

- [x] Describe what changes are being made
- [ ] Explain why and how the changes were necessary and implemented respectively
- [x] Reference issue with `#<ISSUE_NO>` if applicable

#### Resources

- [ ] If you have changed any SCSS code, run `make release` to regenerate all CSS files

#### Contributors

- [x] Add yourself to `CONTRIBUTORS.md` if you aren't on it already

### CODE REVIEW

**Comment by luizdepra** [comment]
I think you unintentionally removed the `post` translation. Could you add it again, please?

**Comment by clement-pannetier** [comment]
@luizdepra I made a typo in the wiki, I wrote "Bangali" instead of "B**e**ngali" or "Bangla". Sorry 😶.

**Comment by arafat-hasan** [comment]
> I think you unintentionally removed the `post` translation. Could you add it again, please?

Oops, I have pushed another. I did that intentionally though, as there was no `post` in the English version then so I dropped it.



> @luizdepra I made a typo in the wiki, I wrote "Bangali" instead of "B**e**ngali" or "Bangla". Sorry no_mouth.

It doesn't matter.  We, native speakers, call the language Bangla, Bengali in English utterance. Bangla-Bengali-Bangali makes confusion actually.

**Comment by luizdepra** [comment]
> Oops, I have pushed another. I did that intentionally though, as there was no post in the English version then so I dropped it.

Yeah, It was missing there too. xD

Thank you again.

**Pull request merged**
