### PR TITLE
Add an optional featured image

### PR DESCRIPTION
**Pull request by bobbywlindsey**
### Description

This pull request adds an optional feature to include a featured image to your post. All you need to do is add `featured_image: 'url_link'` to your post's front matter.

### CODE REVIEW

**Comment by luizdepra** [comment]
Nice.
Could you please modify or add a new post in the `exampleSite` to show these new features?

**Comment by bobbywlindsey** [comment]
@luizdepra I modified the "Getting Started with Hugo post", but seem to be having some formatting issues with the Table of Contents piece. Will investigate documentation unless you might know what's causing it.

**Comment by luizdepra** [comment]
It seems the TOC feature is creating a `ul` element of the TOC Itens inside another `ul`. I never used the TOC, so I don't have any idea why this problem happens. Maybe it is a `markup` bug?

**Comment by bobbywlindsey** [comment]
@luizdepra Couldn't figure out what it was. I might take another try at it later on. For now I'll just include the optional feature of including a post image.

**Comment by RagnarGrootKoerkamp** [comment]
For others where it doesn't work: note that this was renamed to `featuredImage`.

**Pull request merged**
