### PR TITLE
some features and fixes

### PR DESCRIPTION
**Pull request by pduchnovsky**
### Prerequisites

- [x] This pull request adds a feature.
- [x] This pull request fixes certain issues.

### Description

- Some very minor changes in css
- Removed prefetch-src CSP since its deprecated and unsupported by any browser
- Added support for "mailto:" e.g. 'Contact me' menu links.
e.g.: image
- Lowered text size of footer on mobile devices.
e.g. before and after:
image

### Issues Resolved

- Defined avatar width and height so content doesn't 'jump' during page/image loading.
- Added pagination li padding for more easily 'clickable' pagination links on mobile devices and some other minor changes.
e.g. before and after:
image
- Increased size of avatar on mobile devices so it does not look so small.
e.g. before and after:
image

#### General

- [x] Describe what changes are being made
- [x] Explain why and how the changes were necessary and implemented respectively

#### Resources

- [x] If you have changed any SCSS code, run `make release` to regenerate all CSS files

### CODE REVIEW

**Comment by luizdepra** [comment]
I'm going to need to merge this PR in a separated branch, and then I can cherry-pick the changes I find interesting.
I'll come back here later.

**Comment by mrhappyma** [comment]
this is nice, please merge this 😀

**Comment by pduchnovsky** [comment]
Just a note, this is ready to be merged still :D I think the changes are pretty useful, not sure what's the blocker ¯\_(ツ)_/¯

**Comment by luizdepra** [comment]
> Just a note, this is ready to be merged still :D I think the changes are pretty useful, not sure what's the blocker ¯_(ツ)_/¯

I still want to cherry-pick some of your contributions. But, I don't have the time right now. :/

**Comment by pduchnovsky** [comment]
@luizdepra I mean it's just like 20 lines of actual new/changed code, if I were you I'd just merge it, it is ready.. changes are explained and non breaking, cosmetic mostly.

**Comment by luizdepra** [comment]
@pduchnovsky, sure. Last time I checked there were lots and many changes, so, my bad for not reviewing again. Well, everything looks good to me. Thank you for the effort and patience.

**Pull request merged**
