### PR TITLE
Fix code indent

### PR DESCRIPTION
**Pull request by nysthee**
# Pull Request Checklist

- [x] Describe what changes are being made
Fix the indent of the first line of a code block.
- [x] Explain why and how the changes were necessary and implemented respectively
Because of symmetry. 😄 
- [x] Reference issue with `#<ISSUE_NO>` if applicable
I believe this regression was already discussed here: https://github.com/luizdepra/hugo-coder/issues/38
- [x] If you have changed any SCSS code, run `make release` to regenerate all CSS files.
- [x] Add yourself to `CONTRIBUTORS.md` if you aren't on it already

### CODE REVIEW

**Comment by nysthee** [comment]
Hm it causes a regression for inline code.

**Comment by luizdepra** [comment]
Looks fine in Firefox. Maybe this problem is browser specific?

**Comment by nysthee** [comment]
I changed the code :)

**Comment by nysthee** [comment]
That's weird it ran make release.

**Comment by nysthee** [comment]
ha i will do a rebase

**Comment by nysthee** [comment]
hm weird i am up to date with master locally

**Comment by luizdepra** [comment]
GitHub says that yout fork is one commit behind `luizdepra:mastet`. So, you need sync your fork, doing a fetch from upstream.

**Comment by nysthee** [comment]
Ha  I keep forgetting that one.
Repushed.

**Comment by luizdepra** [comment]
Hahha! Np.
Thank you for the fix.

**Pull request merged**
