### PR TITLE
Taxonomies list as a tag cloud

### PR DESCRIPTION
**Pull request by sdwolfz**
### Prerequisites

Put an `x` into the box(es) that apply:

- [ ] This pull request fixes a bug.
- [x] This pull request adds a feature.
- [ ] This pull request introduces breaking change.

### Description

Inspired by this: https://adityatelange.github.io/hugo-PaperMod/tags/

Changed taxonomy lists (terms) to display a tag cloud instead of a paginated list. Seems more appropriate since those lists are usually smaller that the content list and it's more important to browse them all and see how many articles they reference instead of having a chronological list IMHO. Content lists are not affected.

Looks like this:

tags-dark
tags-dark-single
tags-light
tags-light-single

### CODE REVIEW

**Comment by luizdepra** [comment]
Interesting. Thanks for contributing.

I was testing this PR and I saw that the new tag  styling is now working. See [here](https://deploy-preview-557--hugo-coder.netlify.app/tags/).
Maybe you forgot to regenerate the CSS files with `make release`? Could you please take a look on that?

**Comment by sdwolfz** [comment]
@luizdepra I'm having trouble doing that:

```
$ make release
hugo --themesDir=../.. --source=exampleSite
Total in 1 ms
Error: module "hugo-coder" not found; either add it as a Hugo Module or store it in "/here/themes".: module does not exist
make: *** [Makefile:6: build] Error 255
```

**Comment by sdwolfz** [comment]
@luizdepra never mind, I had the theme directory renamed as I'm running from a fork, try now.

**Review by luizdepra — APPROVED** [review]
LGTM

Probably I'm going to change something about the styling later, but so far, so good.

Thank you. :)

**Pull request merged**
