### PR TITLE
match the footer font style to the header

### LINKED ISSUE #493: modify footer font family to match header?
Hi,

Thanks for your work on this theme!

After applying coder to my site one little nit that struck me as odd was that the font family of the footer didn't match the header. I'm not a font expert but I believe the header uses sans-serif and the body uses serif. To my eyes it looks weird for the footer to also use serif.

I'm also not a CSS expert but I was able to produce the behavior I wanted with this one-liner:

```
diff --git a/assets/scss/_footer.scss b/assets/scss/_footer.scss
index 286c393..623efa0 100644
--- a/assets/scss/_footer.scss
+++ b/assets/scss/_footer.scss
@@ -1,6 +1,7 @@
 .footer {
   width: 100%;
   text-align: center;
+  font-family: $heading-font-family;
   line-height: 2.0rem;
   margin-bottom:1.0rem;
   a {
```

Of course this may just be my taste preference but I wanted to ask if you'd accept a PR that contains this patch?

Thanks in advance.

### PR DESCRIPTION
**Pull request by bfallik**
With this change both the header and the footer use sans-serif which
looks more consistent in a page with a serif body.

### Prerequisites

Put an `x` into the box(es) that apply:

- [ ] This pull request fixes a bug.
- [X] This pull request adds a feature.
- [ ] This pull request introduces breaking change.

### Description

Add a style to the footer that matches the header.

### Issues Resolved

Resolves #493.

### Checklist

Put an `x` into the box(es) that apply:

#### General

- [X] Describe what changes are being made
- [X] Explain why and how the changes were necessary and implemented respectively
- [X] Reference issue with `#<ISSUE_NO>` if applicable

#### Resources

- [X] If you have changed any SCSS code, run `make release` to regenerate all CSS files

#### Contributors

- [ ] Add yourself to `CONTRIBUTORS.md` if you aren't on it already

### CODE REVIEW

**Comment by bfallik** [comment]
Hi! Just wanted to raise visibility on this PR and get feedback on a possible merge. Thx in advance.

**Comment by luizdepra** [comment]
Sorry for taking to long to come back here. I'm recovering from a burnout, so I'm taking easy to come back to normal routine.

So, your PR is fine. I just need to fix the conflicts. Don't worry, I can do that. But I need to merge one or another PR ahead of this one.

**Comment by bfallik** [comment]
@luizdepra Thanks for getting back to me! I was worried my PR got lost.

Burnout is no joke so definitely don't stress about this. That being said the PR is incredibly small so whenever you're ready to review+merge it'd be hard to find an easier warm up. =)

**Comment by luizdepra** [comment]
Thank you. :)

**Pull request merged**
