### PR TITLE
Fixes 👌 / Changes 👊 /  Features 🙌

### PR DESCRIPTION
**Pull request by pduchnovsky**
First and foremost -> This theme is A W E S O M E, good job !

- [x] This pull request fixes a bug. #441 
- [x] This pull request adds several features

### Description

**Fixes**:
  - Fixed avatar pop-in and text movement after avatar loading by defining width/height of avatar
  - Fixed issue with blinking background when non-native color mode is set due to lack of cache definition for .js files on hosting provider side - moved script contents to html code directly, which is the correct way for such critical js code.
  - Fixed floating button line height on mobile devices
  - Fixed mouse pointer near homepage icons (it was sometimes switching to select text pointer)

**Changes**:
  - Now most scss/css files are merged during build and loaded just once to improve speed
  - Enlarged avatar a little bit, it was way too small on mobile devices
  - Made pagination links easier to click on mobile devices by adding padding
  - Made fonts even smaller on mobile devices, were too big compared to even enlarged avatar
  - Disabled selection of images and right-click action.

**Features**:
  - Added `enablePostSummary` feature to show summary of blog post
  - Added `enablePostImg` feature to show img preview of blog post
    -  Works with 'images' variable, either Site.Param or Page.Param..
    -  e.g.: `images = ["/images/test/jpg"]`, same as twitter card image does.
  - Added `showRecent` feature that works with above, to show **X** last posts on homepage
    - ^also added translations for new texts
  - Added `disqusOnClick` feature that when enabled prevents disqus to automatically loading, instead there is a button for this
    - This button also shows comment count
  - Added `rtimeMeta` option for reading time metadata on twitter cards (works for slack and maybe others, but not twitter/fb - hugo uses twitter card 'summary large image' by default when images are specified/found in article)
  - Added (automatic) native image lazy loading as well as defining of width/height (for images on posts/pages), this is in /layouts/_default/_markup/render-image.html.
  - Added support for 'mailto:' links in menu
  - Added enhanced scrollbar design that does not interfere with page
  - Added css-only 'gallery' functionality as well as simple alignment of images
    - Examples of alt text for specific alignment, basically `_gallery` limits max width to 49% so images fit next to each other:
    `_gallery <` gallery left
    `_gallery >` gallery right
    `` center only
    `` left only
    `` right only
  Gallery example is also added to the example site, or check out [this link](https://pduchnovsky.com/2020/11/gallery-function-css/) for more details.

### CODE REVIEW

**Comment by luizdepra** [comment]
Thanks for the compliment, @pduchnovsky. :smile: 

I think there is no subtle way to say, but this PR is kind of... massive. :laughing:
There is a lot of changes and additions to review here. But don't worry, I'm not closing and forgetting what you made here. I want to understand and select good features and changes. Yes, I probably will not accept some of your changes because they might be more like personal customizations, or I might judge it as no suitable for the project.
So, I need some time to go over all these changes and see what I want or not. After that, I'll need your help to break thing in smaller PRs.

I need to say that I work on an e-commerce company, and Black Friday is just around the corner. I'll be very busy these next 2 or 3 weeks. So, stay put, I'll back here later.

**Comment by pduchnovsky** [comment]
@luizdepra thanks, well, it only looks massive because of a lot of assets from forkawesome
It is not actually altering this theme design over all, all options are optional and can be turned off by default 👍 
It only adds features that I wished were here so I added them :)

**Comment by pduchnovsky** [comment]
I removed twemoji self-hosting from this PR in order to make the changes more readable and will create a new PR for that change :)

**Comment by xp-vit** [comment]
That is such a great PR with so many nice improvements. However, it contains too much changes and I understand why owner of the repo is slow in revieving/merging of this PR. Shall we probably split it into features and go 1 by 1?

**Comment by pduchnovsky** [comment]
> That is such a great PR with so many nice improvements. However, it contains too much changes and I understand why owner of the repo is slow in revieving/merging of this PR. Shall we probably split it into features and go 1 by 1?
tbh, I don't really have time now to split it, splitting is a lot of effort as well, as I see it, it fixes bunch of minor things and adds bunch of optional features that don't really break anything as far I see so, I understand it's a lot of changes, but I already invested a lot of time in it and don't have spare time to split it right now :(

**Comment by xp-vit** [comment]
> > That is such a great PR with so many nice improvements. However, it contains too much changes and I understand why owner of the repo is slow in revieving/merging of this PR. Shall we probably split it into features and go 1 by 1?
> 
> tbh, I don't really have time now to split it, splitting is a lot of effort as well, as I see it, it fixes bunch of minor things and adds bunch of optional features that don't really break anything as far I see so, I understand it's a lot of changes, but I already invested a lot of time in it and don't have spare time to split it right now :(

Totally understand you. Let's see if @luizdepra is able to review this PR and see what we can do.

**Comment by xp-vit** [comment]
@pduchnovsky  do you want to pull upstream master to your branch?

**Comment by pduchnovsky** [comment]
> @pduchnovsky do you want to pull upstream master to your branch?

done

**Comment by luizdepra** [comment]
I probably will cherry-pick changes from this PR.
There are many things in my queue right now, I can't promise to do it so soon.

**Comment by pduchnovsky** [comment]
I am moving all custom stuff to my web repository and will ocassionally push some new features but for now im closing this PR.

**Pull request closed without merging**
