### PR TITLE
add connect-src, add badges to home.html

### PR DESCRIPTION
**Pull request by cageyv**
### Prerequisites

Put an `x` into the box(es) that apply:

- [ ] This pull request fixes a bug.
- [x] This pull request adds a feature.
- [ ] This pull request introduces breaking change.

### Description

- add connect-src: solve problem with google-analytic
- add badges to home.html: Many IT specialists receive certificates, take tests and often receive digital badges as a reward
- live-demo: [https://cageyv.dev/](https://cageyv.dev/)

### Issues Resolved

List any existing issues this pull request resolves.

### CODE REVIEW

**Comment by cageyv** [comment]
`
10:23:42 PM: Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: _default/single.html:11:9: executing "_default/single.html" at <partial "csp.html" .>: error calling partial: "/opt/build/repo/demo/themes/hugo-coder/layouts/partials/csp.html:1:649": execute of template failed: template: partials/csp.html:1:649: executing "partials/csp.html" at <delimit .Site.Params.csp.connectsrc " ">: error calling delimit: can't iterate over <nil>
`

**Comment by luizdepra** [comment]
Hey @cageyv. First, thanks for your contribution.
I'm happy with the `connect-src` fix, but the badge feature is the kind of personal customization that I want to avoid to add to the main theme. I encourage you to keep this kind of modification in a personal fork.

So, could you please modify this PR to contain only the `connect-src` fix? Thank you. :)

**Comment by cageyv** [comment]
@luizdepra okay, sure I will modify it soon

**Comment by maynagashev** [comment]
I've created new issue for connect-src #547 & pull request with connect-src only #548

**Pull request closed without merging**
