### PR TITLE
Change link styles when in a post

### PR DESCRIPTION
**Pull request by Vlaaaaaaad**
The difference between bolded text and links/ anchors was almost none which lead to confusion and having to hover to see which words are links and which ones are bold.

This commit implements best practices for accessibility by having links in posts( and **only in posts**) be underlined.

**Before**:
screen shot 2018-04-29 at 10 38 29

**After**:
screen shot 2018-04-29 at 10 39 59

### CODE REVIEW

**Comment by mbollemeijer** [comment]
I also would like to see this change.

**Comment by luizdepra** [comment]
Nice.

Can you update your fork and generate `style.min.css` again?
There is a conflict with another previously merged PR.

**Comment by Vlaaaaaaad** [comment]
Done! This can now be merged.

**Comment by luizdepra** [comment]
Thank you!

**Pull request merged**
