### PR TITLE
web safe fonts

### PR DESCRIPTION
**Pull request by pduchnovsky**
### Prerequisites

- [X] This pull request adds a feature.

### Description

Changes google fonts to web-safe fonts (system default fonts)

#### Resources

- [X] If you have changed any SCSS code, run `make release` to regenerate all CSS files

#### Contributors

- [X] Add yourself to `CONTRIBUTORS.md` if you aren't on it already

### CODE REVIEW

**Review by carvalholeo — APPROVED** [review]

**Comment by pduchnovsky** [comment]
Resolved conflicts in advance for smooth merge.

**Review by iamrajiv — APPROVED** [review]

**Comment by luizdepra** [comment]
Thank you.
Probably I'm going to change some sizes or spacing later. But it really looks fine.

**Comment by artspb** [comment]
Hey. Just wanted to check with you. On macOS, the new font looks significantly different. Is it expected? Is it how the theme should look like since this PR or is it a bug/misconfiguration?

fonts

**Comment by luizdepra** [comment]
Yep. It will look different because instead using custom fonts we are using system default fonts from each OS.

**Comment by artspb** [comment]
I see. The answer is probably obvious but I'm not a web developer, so I'd still prefer to ask. What's the reason behind this change? Subjectively, I like the look on the left more.

**Comment by luizdepra** [comment]
The idea is to make the theme lighter and get a faster loading time.

But, it kind of easy to revert these changes. You can fork the project, or just edit locally, and undo this PR or use font-faces directly into SCSS files.

**Comment by artspb** [comment]
Thanks. Maintaining a fork could become troublesome over time. I was hoping to find a way to overwrite the font via custom CCS. Any advice is welcome 🙃

**Comment by luizdepra** [comment]
Hmm. Yeah, It is possible too, I guess.
Maybe creating a custom CSS file that import the old fonts with `@import url(...)`, and also setting `font-familly` in the right places, Yeah, I think it will work.

**Comment by artspb** [comment]
This is what I've ended up with in case someone needs it. The only problem is that without `preload` for gstatic, a page blinks after being loaded. I see no way to fix it other than by replacing `baseof.html` locally. Still, it seems easier to maintain than a fork. Thanks for the advice, by the way!

```fonts.css
@import url("https://fonts.gstatic.com");
@import url("https://fonts.googleapis.com/css?family=Lato:400,700%7CMerriweather:300,700%7CSource+Code+Pro:400,700&display=swap");

:root {
    --text-font-family: Merriweather, Georgia, serif;
    --heading-font-family: Lato, Helvetica, sans-serif;
    --code-font-family: 'Source Code Pro', 'Lucida Console', monospace;
}

body {
    font-family: var(--text-font-family);
    font-size: 1.6em;
    font-weight: 300;
}

a {
    font-weight: 300;
}

h1,
h2,
h3,
h4,
h5,
h6 {
    font-family: var(--heading-font-family);
    font-weight: 700;
    margin: 6.4rem 0 3.2rem 0;
}

.list ul li .title,
.footer,
.pagination {
    font-family: var(--heading-font-family);
}

.navigation a,
.navigation span {
    font-size: 1.6rem;
    font-family: var(--heading-font-family);
    font-weight: 700;
}

pre,
code {
    font-family: var(--code-font-family);
}
```

**Pull request merged**
