### PR TITLE
Add apple touch icon

### PR DESCRIPTION
**Pull request by bebound**
### Prerequisites

Put an `x` into the box(es) that apply:

- [ ] This pull request fixes a bug.
- [x] This pull request adds a feature.
- [ ] This pull request introduces breaking change.

### Description

By adding `touchicon` param in `config.toml` `params` section, the website will show icon in safari bookmark.

`touchicon = "/icons/icon-180x180.png"`

Screen Shot 2020-08-01 at 22 30 32

PS:
Sorry, the commits is messy. I guess squash and merge should fix this. If not, I can create another PR.

### Issues Resolved

List any existing issues this pull request resolves.

### Checklist

Put an `x` into the box(es) that apply:

#### General

- [x] Describe what changes are being made
- [x] Explain why and how the changes were necessary and implemented respectively
- [x] Reference issue with `#<ISSUE_NO>` if applicable

#### Resources

- [ ] If you have changed any SCSS code, run `make release` to regenerate all CSS files

#### Contributors

- [x] Add yourself to `CONTRIBUTORS.md` if you aren't on it already

### CODE REVIEW

**Comment by luizdepra** [comment]
How about just creating a default icon for the theme, like the others ones, instead of creating a new configuration?

**Comment by bebound** [comment]
Can I put the default touch icon in  `/images/touch-icon.png`?

How about change the config similar to this?

`<link rel="icon" type="image/png" href="{{ .Site.Params.favicon_16 | default "/images/favicon-16x16.png" | absURL }}" sizes="16x16">`

**Comment by luizdepra** [comment]
> Should I put the default touch icon in /images/touch-icon.png?

Yup.

> How about change the config similar to this?

Sure. You got it.
We need to use a default touch icon if none is provide.

**Comment by bebound** [comment]
Okay, thanks. I’ll do this later.

**Comment by bebound** [comment]
Hi, I've update the code.

**Comment by luizdepra** [comment]
The icon will be missing, but I will add it later. No worries.

**Pull request merged**
