### PR TITLE
Add Stackbit Integration

### PR DESCRIPTION
**Pull request by JugglerX**
### Prerequisites

Put an `x` into the box(es) that apply:

- [ ] This pull request fixes a bug.
- [x ] This pull request adds a feature.
- [ ] This pull request introduces breaking change.

### Description

This pull request add's Stackbit to this Hugo theme. It add's the `stackbit.yaml` file which makes this theme work with several headless CMS automatically (including Forestry, NetlifyCMS, DatoCMS & Contentful) and it deploys the site to Netlify in 1 click.

You can try it out: https://app.stackbit.com/create?theme=https://github.com/stackbithq/hugo-coder (note the "create with stackbit" button in the readme will import the theme from your repo so until the PR is merged it wont work)

### Issues Resolved

List any existing issues this pull request resolves.

### Checklist

Put an `x` into the box(es) that apply:

#### General

- Add `stackbit.yaml` file which makes the theme work with Stackbit.
- Updated 2 posts changing `math` and `katex` from string values to booleans

#### Resources

- [ ] If you have changed any SCSS code, run `make release` to regenerate all CSS files

#### Contributors

- [ ] Add yourself to `CONTRIBUTORS.md` if you aren't on it already

### CODE REVIEW

**Comment by luizdepra** [comment]
We'll need to add every possible configuration into `stackbit.yaml`? Because there some missing, also Hugo has many other confiurations.

**Comment by JugglerX** [comment]
Hey, this is working as is. Which configuration options are missing?

**Comment by JugglerX** [comment]
Anything I can do here to progress this PR?

**Comment by luizdepra** [comment]
> Do you mean supporting uncommented options in the config? Or do you mean supporting undeclared default hugo params in the config?
Both I think. If the user will need one or more configurations not declared in the `stackbit.yam`, what she/he will need to do to use the configuration?

I just don't get the usage here. The `stackbit.yaml` file is just a base for demo deploy on Stackbit or it is used to configure a new sites? The users will need to copy this file into their site repo?

**Comment by JugglerX** [comment]
It let's people use this theme with Stackbit. It will clone this theme, connect it to any headless CMS and deploy it to Netlify.

best thing is to just try it: https://app.stackbit.com/create?theme=https://github.com/stackbithq/hugo-coder

**Comment by luizdepra** [comment]
I see the value here, but I wanted to make sure that `stackbit.yaml` must be added to this repo. Now I understand.

I will  approve this PR now. But, because I don't use stackbit, if some issue come up in the future I will mention you to help, ok?

**Comment by JugglerX** [comment]
Thanks for merging!

Sure, If people create issues related to Stackbit I'll be happy to put in fixes. If it becomes too difficult to "support", all you need to do is remove the stackbit.yaml file. The integration is really easy to remove and doesn't effect your existing theme.

**Pull request merged**
