### PR TITLE
Fix burger focus color change

### PR DESCRIPTION
**Pull request by sdwolfz**
### Prerequisites

Put an `x` into the box(es) that apply:

- [x] This pull request fixes a bug.
- [ ] This pull request adds a feature.
- [ ] This pull request introduces breaking change.

### Description

Reference: https://github.com/luizdepra/hugo-coder/pull/333

:point_up: Fixing the bug detailed in the PR above by forcing the css of the burger menu button to not have a focus color change.

### CODE REVIEW

**Comment by luizdepra** [comment]
Nice. Could you please update the generated css files with `make release` and add these new files to this PR?

**Comment by sdwolfz** [comment]
Running `make release` simply deletes files in `resources/_gen`. Is this the intended result? (if yes I can squash).

Also, please don't put a hacktoberfest label on this PR, I don't participate in that spam.

**Comment by sdwolfz** [comment]
:point_up: Never mind, I was compiling with arch hugo instead of the extended version. Pushed the changes. Let me know if it's OK.

Also, do you want a docker image for the project? Here's the one I use: https://gitlab.com/sdwolfz/docker-images/-/blob/master/hugo/Dockerfile

You can run it with `docker run --rm -it sdwolfz/hugo:latest sh` but I think it's better to have it part of the project, and it does not have rsync as I don't use that.

**Comment by luizdepra** [comment]
Well, this project is just a theme. Adding docker to build its demo is kinda overkill and one more thing to update (or forget to). So, I prefer to not include a dockerfile here. 

About your PR. I tried to test in on my phone but the problem is still there. Maybe my phone is caching something. I'll try it again later.

**Comment by luizdepra** [comment]
I think I found the problem. We need to add the same rule into `_navigation_dark.scss`.

**Comment by sdwolfz** [comment]
Firefox touch simulation was not triggering the rule so I thought it worked :see_no_evil: 

Pushed dark mode changes.

**Review by luizdepra — APPROVED** [review]
Nice. Now it is working fine.
Thank you.

**Pull request merged**
