### PR TITLE
Add support for using as a Hugo module

### LINKED ISSUE #502: Support for hugo module
Hello,

I was recently to get this theme working with hugo module, but it doesn't seem to work. 

```bash
❯ hugo new site karthik
...
❯ hugo mod init karthik
go: creating new go.mod: module karthik
❯ hugo mod get -u

hugo: downloading modules …
go: github.com/luizdepra/hugo-coder upgrade => v0.0.0-20201215193806-dbe21a7fdf0d
hugo: collected modules in 3793 ms
❯ hugo serve -D
Start building sites …
WARN 2021/01/01 15:17:28 found no layout file for "HTML" for kind "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2021/01/01 15:17:28 found no layout file for "HTML" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2021/01/01 15:17:28 found no layout file for "HTML" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.

                   | EN
-------------------+-----
  Pages            |  3
  Paginator pages  |  0
  Non-page files   |  0
  Static files     |  0
  Processed images |  0
  Aliases          |  0
  Sitemaps         |  1
  Cleaned          |  0

Built in 1 ms
Watching for changes in /Users/temporaryadmin/karthik/{archetypes,content,data,layouts,static}
Watching for config changes in /Users/temporaryadmin/karthik/config.toml, /Users/temporaryadmin/karthik/go.mod
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at //localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
WARN 2021/01/01 15:17:40 found no layout file for "HTML" for kind "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
```

Whereas my config is
```toml
[module]
  [[module.imports]]
    path = "github.com/luizdepra/hugo-coder"


theme = "hugo-coder"


baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
```

### PR DESCRIPTION
**Pull request by freeformz**
### Prerequisites

Put an `x` into the box(es) that apply:

- [ ] This pull request fixes a bug.
- [x] This pull request adds a feature.
- [ ] This pull request introduces breaking change.

### Description

Adds appropriate files/updates example site to use modules.

You can see it being used here: https://github.com/freeformz/icanhazdowntime.org

### Issues Resolved

Fixes #502

### Checklist

Put an `x` into the box(es) that apply:

#### General

- [x] Describe what changes are being made
- [x] Explain why and how the changes were necessary and implemented respectively
- [x] Reference issue with `#<ISSUE_NO>` if applicable

#### Resources

- [ ] If you have changed any SCSS code, run `make release` to regenerate all CSS files

#### Contributors

- [x] Add yourself to `CONTRIBUTORS.md` if you aren't on it already

### CODE REVIEW

**Comment by freeformz** [comment]
The netlify builds are stuck *at least* because the go version installed (go 1.10) doesn't support modules. I'm not sure how to tell netlify how to use/install a newer version of go.

**Comment by freeformz** [comment]
I *think* the version of go depends on the version of the base image you are using. That doesn't exactly make sense because I've seen other netlify build output with even newer version of go, than what is in the images, so 🤷 

Relevant links: https://docs.netlify.com/functions/build-with-go/#build-settings-and-dependency-management and https://docs.netlify.com/configure-builds/get-started/#build-image-selection and https://github.com/netlify/build-image/blob/xenial/included_software.md

**Comment by freeformz** [comment]
Fixed. Let me know if you want me to clean anything up.

**Comment by luizdepra** [comment]
Thanks. This PR looks really fine. But I just changed some rules inside Makefile and netlify.toml, so I'm going to merge your PR in a different branch and fix everything first.

**Pull request merged**
