### PR TITLE
Fixed code block background color

### PR DESCRIPTION
**Pull request by LanskovNV**
### Prerequisites

Put an `x` into the box(es) that apply:

- [x] This pull request fixes a bug.
- [ ] This pull request adds a feature.
- [ ] This pull request introduces breaking change.

### Description

This pull request fix code block background color. I made it more contrast at light/dark themes and now it's much more
comfortable to read code on codeblocks

### Checklist

Put an `x` into the box(es) that apply:

#### General

- [x] Describe what changes are being made
- [x] Explain why and how the changes were necessary and implemented respectively
- [ ] Reference issue with `#<ISSUE_NO>` if applicable

#### Resources

- [x] If you have changed any SCSS code, run `make release` to regenerate all CSS files

#### Contributors

- [x] Add yourself to `CONTRIBUTORS.md` if you aren't on it already

### CODE REVIEW

**Review by wanglinteng — COMMENTED** [review]
Amazing!

**Comment by 11nightfury** [comment]
I'm facing same problem, when will this pull request be merged?

**Comment by LanskovNV** [comment]
> I'm facing same problem, when will this pull request be merged?
> 
> EDIT: as per #567, using `pygmentsStyle = "native"` seems to work for now.

Sounds interesting. Thank you for comment,  I'll check this solution.

**Comment by luizdepra** [comment]
I think `!important` might override any custom highlight theme. Let me test it here first.

**Comment by luizdepra** [comment]
This will work fine if `bw` highlight color scheme (or maybe similar ones), but will look weird with monokai and others. This is fine, there is no current good approach to solve this problem without using custom CSS for dark and light color schemes.

I just merged your PR manually, fixing some conflict issues. So, closing here. Thank you!

**Comment by 0rzech** [comment]
This PR made pygments' `paraiso-dark` style completely unusable for me. I think that such dramatic change should be implemented as another pygments style instead of overriding whatever one sets in `markup.highlight.style`, especially that it's a built-in Hugo feature.

**Comment by luizdepra** [comment]
I just reverted this changes.

**Comment by 0rzech** [comment]
Thank you! 🙂

**Pull request closed without merging**
