### PR TITLE
Host stuff locally

### PR DESCRIPTION
**Pull request by AltNico**
### Prerequisites

- [ ] This pull request fixes a bug.
- [x] This pull request adds a feature.
- [ ] This pull request introduces breaking change.

### Description

Currently, this theme opens many connections to third-party sites. I'm running this commit [on my webpage](https://nico.dorfbrunnen.eu/) for quite some time without having any problems. This is an rather ugly hack, but I wanted to open this PR in order to discuss a solution similar to this one with the theme's creators.

I hope I don't have to explain all too much why not exposing all visitors to Google etc. is a good thing, but I'll do list some advantages:

* Pretty strong CSP: `content-security-policy: default-src https://nico.dorfbrunnen.eu:443`
* Increased autonomy of webpage; if Google or other CDNs goes down, website still looks good
* When building locally without Internet, everything works fine
* Google is all about surveillance capitalism, they want to collect as much data about people as possible
* With this change, we stop helping them on all websites using this theme
* Google (and the other sites might too) is censored in quite some countries; in all of them, this theme would look not as beautiful as it could

As I said, I don't plan to merge this PR as it is. We have to look into licensing questions and should also structure it better and make it easier to update.

#### General

- [x] Describe what changes are being made
- [x] Explain why and how the changes were necessary and implemented respectively
- [ ] Reference issue with `#<ISSUE_NO>` if applicable

#### Resources

- [X] If you have changed any SCSS code, run `make release` to regenerate all CSS files

#### Contributors

- [X] Add yourself to `CONTRIBUTORS.md` if you aren't on it already

### CODE REVIEW

**Comment by luizdepra** [comment]
Ok, I understand the motivation here and I willing to accept it.
But first I need to understand if there is any license problem if we distribute these fonts with the theme. I'll check this as soon as possible.
Also, I'd prefer if we move these font-faces declarations to an SCSS file instead of a CSS one.
Another thing I want to do is drop fontawesome in favor of SVG Icons, but this fix can be left to another PR.

**Comment by AltNico** [comment]
> I understand the motivation here and I willing to accept it.

Cool :tada: 

> first I need to understand if there is any license problem if we distribute these fonts with the theme.

Sure! Here's what I've found out:

According to [the CSS file we pull from Google](https://fonts.googleapis.com/css?family=Lato:400,700%7CMerriweather:300,700%7CSource+Code+Pro:400,700) we're using three fonts: [Lato](https://fonts.google.com/specimen/Lato), [Merriweather](https://fonts.google.com/specimen/Merriweather) and [Source Code Pro](https://fonts.google.com/specimen/Source+Code+Pro). On the bottom right of those pages it says for all fonts that they are licensed under the [Open Font License ](http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL_web). In its preamble, it says:
> The OFL allows the licensed fonts to be used, studied, modified and redistributed freely as long as they are not sold by themselves. The fonts, including any derivative works, can be bundled, embedded, redistributed and/or sold with any software provided that any reserved names are not used by derivative works.

So I think we're good to go and can include those fonts with the theme.

> I'd prefer if we move these font-faces declarations to an SCSS file instead of a CSS one.

Agreed.

> I want to [...] drop fontawesome in favor of SVG Icons, but this fix can be left to another PR.

Good to know.

**Comment by luizdepra** [comment]
Cool.
So, could you move font-faces declarations to an SCSS in this PR?

Also, I'm in a kind of busy end of the month but I'll try to review and test everything as soon as possible.

**Comment by AltNico** [comment]
@luizdepra Sorry for the delay! I finally managed to finalize this PR.

Like requested by you, I put the fonts css in a scss file. I also found Sass code for fontawesome and normalize and included these in scss, too. Quoting [the huge commit](https://github.com/luizdepra/hugo-coder/pull/194/commits/03437cf179301a9f2aef6c9a527f38169d05942d) (sorry for that!):
> This commit includes the following things to host them locally:
> * fonts (formerly from Google Fonts)
> * fontawesome
> * normalize
> 
> Everything is now included in Sass code. This means not only we no more
have requests to third-party sites, but also reduced the amount of
requests necessary to access the page by three.
> 
> I mainly downloaded all necessary stuff and put it at appropriate
places. I also ran `make release` to regenerate all CSS files.

I understand that reviewing can take some time. I tried to help you by adding links to all resources I used. In the meantime, I'm running this PR [on my webpage](https://nico.dorfbrunnen.eu/).

**Comment by luizdepra** [comment]
Nice. I'll try to review this PR ASAP.

**Comment by AltNico** [comment]
@luizdepra You're welcome! Thank you for maintaining this awesome theme!

The only thing I feel bad about this PR is the decreased maintainability that comes with it. It's not obvious nor easy to update the fontawesome and normalize dependencies at the moment. I'm thinking about pushing an additional updating script that handles downloading the release files and putting it at appropriate places.

Something like this...
```bash
#!/bin/bash
wget https://use.fontawesome.com/releases/v5.10.1/fontawesome-free-5.10.1-web.zip
unzip fontawesome-free-5.10.1-web.zip
rm -r assets/scss/fontawesome/ static/assets/webfonts/
mv fontawesome-free-5.10.1-web/scss/assets/scss/fontawesome/
mv fontawesome-free-5.10.1-web/webfonts/ static/assets/webfonts/
rm -r fontawesome-free-5.10.1-web fontawesome-free-5.10.1-web.zip

wget https://github.com/JohnAlbin/normalize-scss/archive/7.0.1.zip
unzip 7.0.1.zip
rm -r assets/scss/normalize/
mv normalize-scss-7.0.1/sass/ assets/scss/normalize/
rm -r normalize-scss-7.0.1/ 7.0.1.zip
```
Warning: this is neither tested nor optimal from my view. The script needs at least some variables for versions, directories etc. I also thought about using Git submodules or npm packages, but former pulls more than we need and latter introduce a Node.JS dependency we currently don't have. I think, compared to submodules or npm, a script is the way to go. More experienced opinions welcome!

**Comment by luizdepra** [comment]
Well, @AltNico, I think we can handle updating these dependencies manually for now. I want to remove font-awesome, in a near future, and use SVG-based icons instead. And, normalize doesn't release new versions too quickly, so there is no need to keep updating it frequently.

**Comment by luizdepra** [comment]
Ok, this PR looks really good.
I want to use this refactoring as a base to change font-awesome a simpler SVG-based icon library. Also, I need to look for how can I self-host mathjax and other optional dependencies, if possible.

So, I'm going to merge your PR into a separated branch and continue the refactoring there.

**Comment by luizdepra** [comment]
Ty. :)

**Pull request merged**
