### PR TITLE
Use camelCase variables on custom_css, custom_js and custom_scss

### PR DESCRIPTION
**Pull request by Lucas-dOliveira**
### Prerequisites

Put an `x` into the box(es) that apply:

- [ ] This pull request fixes a bug.
- [ ] This pull request adds a feature.
- [X] This pull request introduces breaking change.

### Description

Use camelCase on variables that wasn't respecting this conventions.

### Issues Resolved

https://github.com/luizdepra/hugo-coder/issues/414

### Checklist

Put an `x` into the box(es) that apply:

#### General

- [X] Describe what changes are being made
- [ ] Explain why and how the changes were necessary and implemented respectively
- [X] Reference issue with `#414` if applicable

#### Resources

- [ ] If you have changed any SCSS code, run `make release` to regenerate all CSS files

#### Contributors

- [X] Add yourself to `CONTRIBUTORS.md` if you aren't on it already

### CODE REVIEW

**Comment by luizdepra** [comment]
Nice. Thank you, @Lucas-dOliveira.
I'm going to wait for the `custom_scss` fix here in this PR too, ok?

**Comment by Lucas-dOliveira** [comment]
@luizdepra I also added the customSCSS on the `stackbit.yaml` file because it wasn't there.

**Comment by luizdepra** [comment]
Thank you again. :)

**Comment by clement-pannetier** [comment]
Hey @Lucas-dOliveira, why did you add the `languageinitials` parameter to the `config.toml` file. It's causing issue here #438, I don't see any documentation for this on internet and it's not using in the theme ?!

**Comment by Lucas-dOliveira** [comment]
@clement-pannetier Sorry, after I opened this PR, I started to to work on another issue on this same repository, and I commited by mistake this draft that I was working. This need to be removed! I would appreciate if could fix this.

And again, sorry by this mistake!

**Pull request merged**
