### PR TITLE
New Projects Archetype

### PR DESCRIPTION
**Pull request by clement-pannetier**
### Prerequisites

Put an `x` into the box(es) that apply:

- [ ] This pull request fixes a bug.
- [x] This pull request adds a feature.
- [ ] This pull request introduces breaking change.

### Description

Add a feature requested here #59 and other changes listed below.

### Changes

1. I added a new projects archetype. Now you can create a new content file with `hugo new projects/<filename>.md`.

2. I changed the way taxonomies are listed with `taxonomies.html` ('baseurl'/taxonomy/term) and `terms.html` ('baseurl'/taxonomy).

3. I added a new content/projects to the exampleSite directory and the images associated with the `hugo-coder.md` project file.

4. I added two new scss files to display projects cards in light and dark mode.

5. I added projects layouts files (`list.html`, `li.html` and `single.html`) to display them.

6. I added new properties to the i18n `en.toml` and `fr.toml` files but it's not complete. I struggled with the `one` parameter for `taxonomyCount` property.

### Checklist

Put an `x` into the box(es) that apply:

#### General

- [x] Describe what changes are being made
- [x] Explain why and how the changes were necessary and implemented respectively
- [x] Reference issue with `#<ISSUE_NO>` if applicable

#### Resources

- [x] If you have changed any SCSS code, run `make release` to regenerate all CSS files

### CODE REVIEW

**Comment by clement-pannetier** [comment]
Netlify build error :
> 7:52:25 PM: Error: Error building site: failed to render pages: render of "taxonomy" failed: "/opt/build/repo/demo/themes/hugo-coder/layouts/_default/taxonomy.html:30:31": execute of template failed: template: _default/taxonomy.html:30:31: executing "content" at <.Page.Params.dates>: can't evaluate field Page in type *hugolib.Page

I checked the hugo releases changelog on github, **.Page on taxonomy nodes** is a functionnality added in the [hugo version 0.55.0 release](https://github.com/gohugoio/hugo/releases/tag/v0.55.0).
So I think that's where the error came from.

Why it's such an old version ? I'm running locally the hugo v.0.68.3 without problems.

**Comment by luizdepra** [comment]
I always try to use set the minimal version for the theme. But you can bump it to 0.55 without a problem. Just remember to change it in both `netlify.toml` and `theme.toml`.

**Comment by luizdepra** [comment]
BTW, your PR conflicts with #303.
I'll need some time to review both and maybe merge things.

**Comment by clement-pannetier** [comment]
> I always try to use set the minimal version for the theme. But you can bump it to 0.55 without a problem. Just remember to change it in both `netlify.toml` and `theme.toml`.

Can I just bump to the latest stable version, 0.69.2 ?
I going to test if it indroduces other breaking changes.

**Comment by clement-pannetier** [comment]
> BTW, your PR conflicts with #303.
> I'll need some time to review both and maybe merge things.

I know, css is not the same, layouts too (projects,  taxonomies and terms).

**Comment by clement-pannetier** [comment]
#323

**Pull request closed without merging**
